# Generated by Django 3.1.3 on 2020-11-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
